name: PHP Syntax Checker

on: # 推送或pr分支触发
  push:
    branches: [ master,main ]
  pull_request:
    branches: [ master,main ]

jobs:
  phplint:
    name: PHP Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2' # 指定所需的PHP版本

      - name: Check syntax for changed PHP files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$' > changed_files.txt
          echo "Changed PHP Files:"
          cat changed_files.txt
          while IFS= read -r FILE; do
            if [ -f "$FILE" ]; then
              php -l "$FILE"
              if [ $? -ne 0 ]; then
                echo "Syntax error detected in $FILE"
                exit 1
              fi
            else
              echo "WARNING: File '$FILE' does not exist or is not a regular file."
            fi
          done < changed_files.txt
