name: PHP Syntax Checker

on: # 推送或pr分支触发
  push:
    branches: [ master,main ]
  pull_request:
    branches: [ master,main ]

jobs:
  phplint:
    name: PHP Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2' # 指定所需的PHP版本

      - name: Get list of changed files for a Pull Request # 获取PR的文件列表
        if: github.event_name == 'pull_request'
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.head_ref }} | grep '\.php$' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get list of changed files for a push to main branch  # 获取push的文件列表
        if: github.event_name == 'push'
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Check syntax for changed PHP files
        run: |
          while IFS= read -r FILE; do
            if [ -f "$FILE" ]; then
              php -l "$FILE"
              if [ $? -ne 0 ]; then
                echo "Syntax error detected in $FILE"
                exit 1
              fi
            fi
          done <<< "${{ env.CHANGED_FILES }}"
